/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hieuthuoc.view;

import javax.swing.*;
import java.net.URL;

/**
 *
 * @author PC
 */
public class XemHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form XemHoaDon
     */
    public XemHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLuaChon = new javax.swing.ButtonGroup();
        jPanelHead = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jButtonLapHoaDon = new javax.swing.JButton();
        jButtonXemHoaDon = new javax.swing.JButton();
        jButtonThuoc = new javax.swing.JButton();
        jButtonThongKe = new javax.swing.JButton();
        jButtonNhanVien = new javax.swing.JButton();
        jButtonKhachHang = new javax.swing.JButton();
        jButtonThongTinCaNhan = new javax.swing.JButton();
        jButtonDangXuat = new javax.swing.JButton();
        jPanelThongTinHoaDon = new javax.swing.JPanel();
        jLabelMaSo = new javax.swing.JLabel();
        jTextFieldMaSo = new javax.swing.JTextField();
        jLabelMaSo1 = new javax.swing.JLabel();
        jTextFieldMaSo1 = new javax.swing.JTextField();
        jLabelMaSo2 = new javax.swing.JLabel();
        jTextFieldMaSo2 = new javax.swing.JTextField();
        jLabelMaSo3 = new javax.swing.JLabel();
        jTextFieldMaSo3 = new javax.swing.JTextField();
        jLabelMaSo4 = new javax.swing.JLabel();
        jTextFieldMaSo4 = new javax.swing.JTextField();
        jPanelThongTinChiTietHoaDon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableThongTinChiTietHoaDon = new javax.swing.JTable();
        jPanelDanhSachHoaDon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDanhSachHoaDon = new javax.swing.JTable();
        jPanelChucNang = new javax.swing.JPanel();
        jPanelTimKiem = new javax.swing.JPanel();
        jLabelThongTinTimKiem = new javax.swing.JLabel();
        jTextFieldTimKiem = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jLabelTimTheo = new javax.swing.JLabel();
        jRadioButtonMaHoaDon = new javax.swing.JRadioButton();
        jRadioButtonTenKhacHang = new javax.swing.JRadioButton();
        jRadioButtonTenNhanVien = new javax.swing.JRadioButton();
        jRadioButtonNgayLap = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelHead.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(244, 95, 95));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("XEM HOÁ ĐƠN");

        javax.swing.GroupLayout jPanelHeadLayout = new javax.swing.GroupLayout(jPanelHead);
        jPanelHead.setLayout(jPanelHeadLayout);
        jPanelHeadLayout.setHorizontalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeadLayout.setVerticalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeadLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addContainerGap())
        );

        jPanelMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonLapHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLapHoaDon.setText("Lập hoá đơn");
        jButtonLapHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLapHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonLapHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLapHoaDonActionPerformed(evt);
            }
        });

        jButtonXemHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonXemHoaDon.setText("Xem hoá đơn");
        jButtonXemHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonXemHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonXemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXemHoaDonActionPerformed(evt);
            }
        });

        jButtonThuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonThuoc.setText("Thuốc");
        jButtonThuoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThuoc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThuocActionPerformed(evt);
            }
        });

        jButtonThongKe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonThongKe.setText("Thống kê");
        jButtonThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNhanVien.setText("Nhân viên");
        jButtonNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNhanVienActionPerformed(evt);
            }
        });

        jButtonKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonKhachHang.setText("Khách hàng");
        jButtonKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonThongTinCaNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonThongTinCaNhan.setText("Thông tin cá nhân");
        jButtonThongTinCaNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonThongTinCaNhan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThongTinCaNhanActionPerformed(evt);
            }
        });

        jButtonDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDangXuat.setText("Đăng xuất");
        jButtonDangXuat.setAutoscrolls(true);
        jButtonDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThongTinCaNhan)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButtonThuoc)
                .addGap(6, 6, 6)
                .addComponent(jButtonThongKe)
                .addGap(6, 6, 6)
                .addComponent(jButtonNhanVien)
                .addGap(6, 6, 6)
                .addComponent(jButtonKhachHang)
                .addGap(6, 6, 6)
                .addComponent(jButtonLapHoaDon)
                .addGap(6, 6, 6)
                .addComponent(jButtonXemHoaDon)
                .addGap(6, 6, 6)
                .addComponent(jButtonThongTinCaNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDangXuat)
                .addContainerGap())
        );

        jPanelThongTinHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanelThongTinHoaDon.setForeground(new java.awt.Color(0, 51, 51));

        jLabelMaSo.setText("Mã hoá đơn:");

        jTextFieldMaSo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldMaSo.setToolTipText("");
        jTextFieldMaSo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldMaSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaSoActionPerformed(evt);
            }
        });

        jLabelMaSo1.setText("Ngày lập:");

        jTextFieldMaSo1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldMaSo1.setToolTipText("");
        jTextFieldMaSo1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldMaSo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaSo1ActionPerformed(evt);
            }
        });

        jLabelMaSo2.setText("Nhân viên:");

        jTextFieldMaSo2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldMaSo2.setToolTipText("");
        jTextFieldMaSo2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldMaSo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaSo2ActionPerformed(evt);
            }
        });

        jLabelMaSo3.setText("Khách hàng");

        jTextFieldMaSo3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldMaSo3.setToolTipText("");
        jTextFieldMaSo3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldMaSo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaSo3ActionPerformed(evt);
            }
        });

        jLabelMaSo4.setText("Tổng tiền");

        jTextFieldMaSo4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldMaSo4.setToolTipText("");
        jTextFieldMaSo4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldMaSo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaSo4ActionPerformed(evt);
            }
        });
        URL imgURL = getClass().getResource("/com/hieuthuoc/image/uneti100.jpg");
        ImageIcon icon = new ImageIcon(imgURL);
        JLabel imageLabel = new JLabel(icon);
        imageLabel.setBounds(-12, 380, 160, 175);
        jPanelMenu.add(imageLabel);

        javax.swing.GroupLayout jPanelThongTinHoaDonLayout = new javax.swing.GroupLayout(jPanelThongTinHoaDon);
        jPanelThongTinHoaDon.setLayout(jPanelThongTinHoaDonLayout);
        jPanelThongTinHoaDonLayout.setHorizontalGroup(
            jPanelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabelMaSo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaSo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabelMaSo1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaSo1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addGroup(jPanelThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabelMaSo2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaSo2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addGroup(jPanelThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabelMaSo3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaSo3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                    .addGroup(jPanelThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabelMaSo4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaSo4, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelThongTinHoaDonLayout.setVerticalGroup(
            jPanelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinHoaDonLayout.createSequentialGroup()
                .addGroup(jPanelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaSo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaSo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaSo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaSo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMaSo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaSo2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaSo3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaSo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaSo4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaSo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelThongTinChiTietHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jTableThongTinChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên thuốc", "Đơn vị tính", "Đơn giá", "Số lượng", "Giảm giá", "Thành Tiền"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, String.class, String.class, Double.class, Integer.class, Double.class, Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableThongTinChiTietHoaDon.setShowGrid(true);
        jScrollPane2.setViewportView(jTableThongTinChiTietHoaDon);

        javax.swing.GroupLayout jPanelThongTinChiTietHoaDonLayout = new javax.swing.GroupLayout(jPanelThongTinChiTietHoaDon);
        jPanelThongTinChiTietHoaDon.setLayout(jPanelThongTinChiTietHoaDonLayout);
        jPanelThongTinChiTietHoaDonLayout.setHorizontalGroup(
            jPanelThongTinChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinChiTietHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelThongTinChiTietHoaDonLayout.setVerticalGroup(
            jPanelThongTinChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThongTinChiTietHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDanhSachHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jTableDanhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã hoá đơn", "Ngày lập", "Tổng tiền", "Tên khách hàng", "Nhân viên lập"
            }
        ) {
            Class[] types = new Class [] {
                Integer.class, Integer.class, String.class, Double.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableDanhSachHoaDon.setShowGrid(true);
        jScrollPane1.setViewportView(jTableDanhSachHoaDon);

        javax.swing.GroupLayout jPanelDanhSachHoaDonLayout = new javax.swing.GroupLayout(jPanelDanhSachHoaDon);
        jPanelDanhSachHoaDon.setLayout(jPanelDanhSachHoaDonLayout);
        jPanelDanhSachHoaDonLayout.setHorizontalGroup(
            jPanelDanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelDanhSachHoaDonLayout.setVerticalGroup(
            jPanelDanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDanhSachHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jPanelTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N

        jLabelThongTinTimKiem.setText("Nhập thông tin tìm kiếm:");

        jTextFieldTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimKiemActionPerformed(evt);
            }
        });

        jButtonTimKiem.setText("Tìm kiếm");

        jLabelTimTheo.setText("Tìm theo:");

        buttonGroupLuaChon.add(jRadioButtonMaHoaDon);
        jRadioButtonMaHoaDon.setText("Mã hoá đơn");
        jRadioButtonMaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMaHoaDonActionPerformed(evt);
            }
        });

        buttonGroupLuaChon.add(jRadioButtonTenKhacHang);
        jRadioButtonTenKhacHang.setText("Tên khách hàng");

        buttonGroupLuaChon.add(jRadioButtonTenNhanVien);
        jRadioButtonTenNhanVien.setText("Tên nhân viên");

        buttonGroupLuaChon.add(jRadioButtonNgayLap);
        jRadioButtonNgayLap.setText("Ngày lập");
        jRadioButtonNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNgayLapActionPerformed(evt);
            }
        });

        jButton4.setText("Làm mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTimKiemLayout = new javax.swing.GroupLayout(jPanelTimKiem);
        jPanelTimKiem.setLayout(jPanelTimKiemLayout);
        jPanelTimKiemLayout.setHorizontalGroup(
            jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimKiemLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTimKiemLayout.createSequentialGroup()
                        .addComponent(jLabelTimTheo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButtonTenKhacHang)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTimKiemLayout.createSequentialGroup()
                        .addComponent(jLabelThongTinTimKiem)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTimKiemLayout.setVerticalGroup(
            jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimKiemLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelThongTinTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTimKiemLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTimKiem)
                            .addComponent(jButton4))))
                .addGap(17, 17, 17)
                .addGroup(jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTimTheo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTimKiemLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonMaHoaDon)
                            .addComponent(jRadioButtonTenKhacHang)
                            .addGroup(jPanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonTenNhanVien)
                                .addComponent(jRadioButtonNgayLap)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelChucNangLayout = new javax.swing.GroupLayout(jPanelChucNang);
        jPanelChucNang.setLayout(jPanelChucNangLayout);
        jPanelChucNangLayout.setHorizontalGroup(
            jPanelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelChucNangLayout.setVerticalGroup(
            jPanelChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelThongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelThongTinChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelDanhSachHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanelChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelThongTinChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDanhSachHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(568, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLapHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLapHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLapHoaDonActionPerformed

    private void jButtonXemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXemHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonXemHoaDonActionPerformed

    private void jButtonThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThuocActionPerformed

    private void jButtonNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNhanVienActionPerformed

    private void jButtonDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDangXuatActionPerformed

    private void jButtonThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThongTinCaNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonThongTinCaNhanActionPerformed

    private void jTextFieldTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimKiemActionPerformed

    private void jRadioButtonMaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMaHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMaHoaDonActionPerformed

    private void jRadioButtonNgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNgayLapActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldMaSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSoActionPerformed

    private void jTextFieldMaSo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSo1ActionPerformed

    private void jTextFieldMaSo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSo2ActionPerformed

    private void jTextFieldMaSo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSo3ActionPerformed

    private void jTextFieldMaSo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaSo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaSo4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupLuaChon;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonDangXuat;
    private javax.swing.JButton jButtonKhachHang;
    private javax.swing.JButton jButtonLapHoaDon;
    private javax.swing.JButton jButtonNhanVien;
    private javax.swing.JButton jButtonThongKe;
    private javax.swing.JButton jButtonThongTinCaNhan;
    private javax.swing.JButton jButtonThuoc;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXemHoaDon;
    private javax.swing.JLabel jLabelMaSo;
    private javax.swing.JLabel jLabelMaSo1;
    private javax.swing.JLabel jLabelMaSo2;
    private javax.swing.JLabel jLabelMaSo3;
    private javax.swing.JLabel jLabelMaSo4;
    private javax.swing.JLabel jLabelThongTinTimKiem;
    private javax.swing.JLabel jLabelTimTheo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelChucNang;
    private javax.swing.JPanel jPanelDanhSachHoaDon;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelThongTinChiTietHoaDon;
    private javax.swing.JPanel jPanelThongTinHoaDon;
    private javax.swing.JPanel jPanelTimKiem;
    private javax.swing.JRadioButton jRadioButtonMaHoaDon;
    private javax.swing.JRadioButton jRadioButtonNgayLap;
    private javax.swing.JRadioButton jRadioButtonTenKhacHang;
    private javax.swing.JRadioButton jRadioButtonTenNhanVien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDanhSachHoaDon;
    private javax.swing.JTable jTableThongTinChiTietHoaDon;
    private javax.swing.JTextField jTextFieldMaSo;
    private javax.swing.JTextField jTextFieldMaSo1;
    private javax.swing.JTextField jTextFieldMaSo2;
    private javax.swing.JTextField jTextFieldMaSo3;
    private javax.swing.JTextField jTextFieldMaSo4;
    private javax.swing.JTextField jTextFieldTimKiem;
    // End of variables declaration//GEN-END:variables
}
